### ISSUE TITLE
Kollisionserkennung mittels Collision Mask

### ISSUE THREAD

**Issue by markoczy** [markoczy/2DGameSDK#3]
# Task Beschreibung

## Allgemein

- Ref. Requirement #2

## Definition of Done

- [x] Kollisionsmasken für Entities festlegen
- [x] Berechnung Kollisionsmasken in Welt Koordinaten
- [x] Kollisionspunkt Berechnung
- [x] ~~Kollisionserkennung mittels Polygon Clip Algorithmus~~ Kollisionserkennung mittels Line Intersection
  - [ ] Parallele Kanten
